name: build

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - 'master'
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Prepare
        id: prepare
        run: |
          DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
          DOCKER_IMAGE=ocdev/nebula
          DOCKER_PLATFORMS=linux/amd64,linux/386,linux/ppc64le,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          VERSION=$(curl --silent "https://api.github.com/repos/slackhq/nebula/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')

          TAGS="${DOCKER_IMAGE}:${VERSION}"
          TAGS="$TAGS,${DOCKER_IMAGE}:latest"

          echo "docker_username=${DOCKER_USERNAME}" >> $GITHUB_OUTPUT
          echo "docker_image=${DOCKER_IMAGE}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "docker_platforms=${DOCKER_PLATFORMS}" >> $GITHUB_OUTPUT

          BUILDX_ARGS=$( \
            echo VERSION=${VERSION}; \
            echo BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ'); \
            echo VCS_REF=${GITHUB_SHA::8})
          BUILDX_ARGS="${BUILDX_ARGS//$'\n'/'%0A'}"
          echo "buildx_args=${BUILDX_ARGS}" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.7.0
      -
        name: Checkout
        uses: actions/checkout@v3.5.3
      -
        name: Docker Buildx (build)
        uses: docker/build-push-action@v4.1.1
        with:
          file: Dockerfile
          build-args: ${{ steps.prepare.outputs.buildx_args }}
          context: .
          push: false
          platforms: ${{ steps.prepare.outputs.docker_platforms }}
          tags: ${{ steps.prepare.outputs.tags }}
      -
        name: Docker Login
        if: success() && github.event_name != 'pull_request' && (endsWith(github.ref, github.event.repository.default_branch) || startsWith(github.ref, 'refs/tags/'))
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ steps.prepare.outputs.docker_username }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Docker Buildx (push) - nebula
        if: success() && github.event_name != 'pull_request' && (endsWith(github.ref, github.event.repository.default_branch) || startsWith(github.ref, 'refs/tags/'))
        uses: docker/build-push-action@v4.1.1
        with:
          file: Dockerfile
          build-args: ${{ steps.prepare.outputs.buildx_args }}
          context: .
          push: true
          platforms: ${{ steps.prepare.outputs.docker_platforms }}
          tags: ${{ steps.prepare.outputs.tags }}
      -
        name: Docker Check Manifest
        if: success() && github.event_name != 'pull_request' && (endsWith(github.ref, github.event.repository.default_branch) || startsWith(github.ref, 'refs/tags/'))
        run: |
          docker run --rm mplatform/mquery ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}
